from . import import_history_extend
from . import import_error_extend
from . import brand_mapping
from . import dashboard
from . import direct_import
from . import supplier_mapping_template
from . import product_supplierinfo
from . import product_template
from . import res_partner
from . import import_queue
from . import import_schedule
